### ISSUE TITLE
Dispatch after component unmount

### ISSUE THREAD

**Issue by Ephem** [dai-shi/use-reducer-async#1]
Cool project as always!

One thing I was wondering when I read the src was if you had any ideas on how to ergonomically handle cleaning up the actions if the component unmounts? Consider the example in the Readme:

```jsx
const initialState = {
  sleeping: false,
};

const reducer = (state, action) => {
  switch (action.type) {
    case 'START_SLEEP': return { ...state, sleeping: true };
    case 'END_SLEEP': return { ...state, sleeping: false };
    default: throw new Error('no such action type');
  }
};

const asyncActionHandlers = {
  SLEEP: (dispatch, getState) => async (action) => {
    dispatch({ type: 'START_SLEEP' });
    await new Promise(r => setTimeout(r, action.ms));
    dispatch({ type: 'END_SLEEP' });
  },
};

const Component = () => {
  const [state, dispatch] = useReducerAsync(reducer, initialState, asyncActionHandlers);
  return (
    <div>
      <span>{state.sleeping ? 'Sleeping' : 'Idle'}</span>
      <button type="button" onClick={() => dispatch({ type: 'SLEEP', ms: 1000 })}>Click</button>
    </div>
  );
};
```

If this component unmounts between `START_SLEEP` and `END_SLEEP`, I think the reducer will still run for `END_SLEEP` (possibly indicating a memory leak?), but when the reducer returns new state we're trying to set that on an unmounted component, giving us that dreaded warning.

I think this is a problem that probably affects any library that tries to emit side effects based on dispatches/events btw. In the general sense, if the component is the "owner" of the side effect, how can we cancel it when the component is not around any more?

Is this within scope for this library to provide a mechanism for, or is it something that should be handled in user-land code?

**Comment by dai-shi** [comment]
Thanks for opening up a discussion.

In my [other library](https://github.com/dai-shi/react-hooks-async), I do handle the unmounted status.
The reason I _forgot_ it in this library is that my main use case was [the react-tracked tutorial](https://react-tracked.js.org/docs/tutorial-04), and in such a use case, the component is located near the root which wouldn't be unmounted very often.

> Is this within scope for this library to provide a mechanism for, or is it something that should be handled in user-land code?

This is a good question. Now, this library doesn't have any cancellation mechanism, it should either handle the warning gracefully, or provide a way so that user-land code can handle it.

For any "fetch" libraries, the libraries can handle the unmounted status because they now the data fetching logic. But for "async" libraries that can do any async tasks not limited to data fetching, the situation could be a bit different.

For example, one could do this:
```js
setInterval(() => {
  dispatch({ type: 'PING' });
}, 1000);
```

In such a use case, this library shouldn't crush the react kind warning (indicating a memory leak).

I had been wondering if this library should support abortability before hitting v1.0.0. Yeah, I think it should. (And I should probably remove the unmounted logic from [react-hooks-async](https://github.com/dai-shi/react-hooks-async).)

The little issue is that letting more work in the use-land code is not very handy. The code in README would become not as simple as it is now. 🤔

**Comment by Ephem** [comment]
That all sounds very reasonable! 👍

One thing that I guess could possibly be done is to wrap the `dispatch` to do nothing if the component has unmounted, but I don't think that's a great idea since it just hides the problem and other undesirable side effects would still fire. I also think that this must be dealt with in user-land, but that the library should provide some mechanisms to do so.

I've been thinking about ways to design a good API around this lately, but I haven't come up with any great ideas sadly.

**Comment by dai-shi** [comment]
> One thing that I guess could possibly be done is to wrap the dispatch to do nothing if the component has unmounted, but I don't think that's a great idea since it just hides the problem and other undesirable side effects would still fire.

That's what I do in react-hooks-async without deep thought, but like everyone is doing so...
react-hooks-async already handles cancellation, so no need to hide the warning.

I'll fix both use-reducer-async and react-hooks-async.

Thanks for your insight!
