### ISSUE TITLE
getState immediately after dispatch will return old state

### ISSUE THREAD

**Issue by oswaldoacauan** [dai-shi/use-reducer-async#4]
I have an async action that `dispatch` multiple actions and then call a `getState` to perform the actual async operation, something like this:

```js
const initialState = {
  sleeping: false,
};

const reducer = (state, action) => {
  switch (action.type) {
    case 'START_SLEEP': return { ...state, sleeping: true };
    case 'END_SLEEP': return { ...state, sleeping: false };
    default: throw new Error('no such action type');
  }
};

const asyncActionHandlers = {
  SLEEP: ({ dispatch, getState }) => async (action) => {
    dispatch({ type: 'START_SLEEP' });
	const { sleeping } = getState();
    await new Promise(r => setTimeout(r, isSleeping ? 100000 : 0));
    dispatch({ type: 'END_SLEEP' });
  },
};
```

The expected behavior is that a call to `getState()` immediately after `dispatch()` will return the latest value and that is not the case.

[Here](https://codesandbox.io/s/romantic-swanson-jtowr?file=/src/index.js:541-621) you can find a reproducible example.

**Comment by dai-shi** [comment]
Hi, this behavior is actually unavoidable with React state and to be compatible with Concurrent Mode. In Concurrent Mode, state branches and only one of them is committed after a while.
I know your confusion if your background is redux-thunk or something.
(In that sense, I shouldn't have named like `getState`, because it behaves differently. But, keeping the name would also help by analogy...)

That said, we would like to learn the new pattern. Can you provide your use case? Most likely, we should use local variables instead of `getState`.
